import React from 'react';

export const Box = ({
   children,
   m, mt, mr, mb, ml, // margin, marginTop, marginRight, marginBottom, marginLeft
   p, pt, pr, pb, pl, // padding, paddingTop, paddingRight, paddingBottom, paddingLeft
   color,
   bg, // backgroundColor
   opacity,
   fontFamily,
   fontSize,
   fontWeight,
   fontStyle,
   lineHeight,
   letterSpacing,
   textAlign,
   textTransform,
   w, minW, maxW, // width, minWidth, maxWidth
   h, minH, maxH, // height, minHeight, maxHeight 
   d, // display
   size,
   verticalAlign,
   overflow,
   overflowX,
   overflowY,
   alignItems,
   alignContent,
   justifyItems,
   justifyContent,
   flexWrap,
   flexDirection,
   flex,
   flexGrow,
   flexShrink,
   flexBasis,
   justifySelf,
   alignSelf,
   order,
   gridGap,
   gridRowGap,
   gridColumnGap,
   gridColumn,
   gridRow,
   gridArea,
   gridAutoFlow,
   gridAutoRows,
   gridAutoColumns,
   gridTemplateRows,
   gridTemplateColumns,
   gridTemplateAreas,
   background,
   bgImage, // backgroundImage
   bgSize, // backgroundSize
   bgPos, // backgroundPosition
   bgRepeat, // backgroundRepeat	
   bgAttachment, // backgroundAttachment
   border,
   borderWidth,
   borderStyle,
   borderColor,
   borderTop,
   borderTopWidth,
   borderTopStyle,
   borderTopColor,
   borderRight,
   borderRightWidth,
   borderRightStyle,
   borderRightColor,
   borderBottom,
   borderBottomWidth,
   borderBottomStyle,
   borderBottomColor,
   borderLeft,
   borderLeftWidth,
   borderLeftStyle,
   borderLeftColor,
   borderX,
   borderY,
   borderRadius, 
   borderTopLeftRadius,
   borderTopRightRadius,
   borderBottomRightRadius,
   borderBottomLeftRadius,
   position,
   zIndex,
   top,
   right,
   bottom,
   left,
   textShadow,
   boxShadow,
   animation,
   appearance,
   transform,
   transformOrigin,
   visibility,
   whiteSpace,
   userSelect,
   pointerEvents,
   wordBreak,
   overflowWrap,
   textOverflow,
   boxSizing,
   cursor,
   resize,
   transition,
   objectFit,
   objectPosition,
   fill,
   stroke,
   outline
}) => (
   <div style={{
      margin: m,
      marginTop: mt,
      marginRight: mr,
      marginBottom: mb,
      marginLeft: ml,
      padding: p,
      paddingTop: pt,
      paddingRight: pr,
      paddingBottom: pb,
      paddingLeft: pl,
      color: color,
      backgroundColor: bg,
      opacity: opacity,
      fontFamily: fontFamily,
      fontSize: fontSize,
      fontWeight: fontWeight,
      fontStyle: fontStyle,
      lineHeight: lineHeight,
      letterSpacing: letterSpacing,
      textAlign: textAlign,
      textTransform: textTransform,
      width: w,
      minWidth: minW,
      maxWidth: maxW,
      height: h,
      minHeight: minH,
      maxHeight: maxH,
      display: d,
      size: size,
      verticalAlign: verticalAlign,
      overflow: overflow,
      overflowX: overflowX,
      overflowY: overflowY,
      alignItems: alignItems,
      alignContent: alignContent,
      justifyItems: justifyItems,
      justifyContent: justifyContent,
      flexWrap: flexWrap,
      flexDirection: flexDirection,
      flex: flex,
      flexGrow: flexGrow,
      flexShrink: flexShrink,
      flexBasis: flexBasis,
      justifySelf: justifySelf,
      alignSelf: alignSelf,
      order: order,
      gridGap: gridGap,
      gridRowGap: gridRowGap,
      gridColumnGap: gridColumnGap,
      gridColumn: gridColumn,
      gridRow: gridRow,
      gridArea: gridArea,
      gridAutoFlow: gridAutoFlow,
      gridAutoRows: gridAutoRows,
      gridAutoColumns: gridAutoColumns,
      gridTemplateRows: gridTemplateRows,
      gridTemplateColumns: gridTemplateColumns,
      gridTemplateAreas: gridTemplateAreas,
      background: background,
      backgroundImage: bgImage,
      backgroundSize: bgSize,
      backgroundPosition: bgPos,
      backgroundRepeat: bgRepeat,
      backgroundAttachment: bgAttachment,
      border: border,
      borderWidth: borderWidth,
      borderStyle: borderStyle,
      borderColor: borderColor,
      borderTop: borderTop,
      borderTopWidth: borderTopWidth,
      borderTopStyle: borderTopStyle,
      borderTopColor: borderTopColor,
      borderRight: borderRight,
      borderRightWidth: borderRightWidth,
      borderRightStyle: borderRightStyle,
      borderRightColor: borderRightColor,
      borderBottom: borderBottom,
      borderBottomWidth: borderBottomWidth,
      borderBottomStyle: borderBottomStyle,
      borderBottomColor: borderBottomColor,
      borderLeft: borderLeft,
      borderLeftWidth: borderLeftWidth,
      borderLeftStyle: borderLeftStyle,
      borderLeftColor: borderLeftColor,
      borderX: borderX,
      borderY: borderY,
      borderRadius: borderRadius, 
      borderTopLeftRadius: borderTopLeftRadius,
      borderTopRightRadius: borderTopRightRadius,
      borderBottomRightRadius: borderBottomRightRadius,
      borderBottomLeftRadius: borderBottomLeftRadius,
      position: position,
      zIndex: zIndex,
      top: top,
      right: right,
      bottom: bottom,
      left: left,
      textShadow: textShadow,
      boxShadow: boxShadow,
      animation: animation,
      appearance: appearance,
      transform: transform,
      transformOrigin: transformOrigin,
      visibility: visibility,
      whiteSpace: whiteSpace,
      userSelect: userSelect,
      pointerEvents: pointerEvents,
      wordBreak: wordBreak,
      overflowWrap: overflowWrap,
      textOverflow: textOverflow,
      boxSizing: boxSizing,
      cursor: cursor,
      resize: resize,
      transition: transition,
      objectFit: objectFit,
      objectPosition: objectPosition,
      fill: fill,
      stroke: stroke,
      outline: outline
   }}>
      {children}
   </div>
)